# Generated by Django 4.1.7 on 2023-03-24 18:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('t', 'Tried and true'), ('w', 'Wishlist')], max_length=255)),
                ('prepTime', models.IntegerField()),
                ('yields', models.IntegerField()),
                ('mealType', models.CharField(choices=[('b', 'Breakfast'), ('e', 'Elevenses'), ('l', 'Lunch'), ('s', 'Supper'), ('d', 'dinner')], max_length=255)),
                ('recipe', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
            ],
        ),
    ]
