# Generated by Django 4.1.7 on 2023-03-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReceipAdd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name',
            new_name='mealName',
        ),
    ]
